# Generated by Django 3.1.6 on 2021-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sleekforum', help_text='Website title', max_length=20, verbose_name='site title')),
                ('description', models.TextField(blank=True, help_text='Website metatag description contents', verbose_name='site description')),
                ('email', models.EmailField(default='noreply@localhost', max_length=254, verbose_name='e-mail')),
                ('welcome_mail', models.TextField(blank=True, help_text='message after successful registration', verbose_name='welcome message')),
                ('is_under_maintenance', models.BooleanField(default=False, help_text='Determine if site is under maintenance', verbose_name='maintenance status')),
                ('send_welcome_mail', models.BooleanField(default=False, help_text='Send welcome mail to new users', verbose_name='send welcome email')),
                ('allow_registration', models.BooleanField(default=True)),
                ('captcha', models.BooleanField(default=False, help_text='Turn on/off captcha on pages', verbose_name='captcha verification')),
                ('threads_per_page', models.PositiveSmallIntegerField(default=10, help_text='Number of threads to show on a page', verbose_name='threads on a page')),
                ('posts_per_thread', models.PositiveSmallIntegerField(default=10, help_text='Number of posts to display per thread', verbose_name='posts per thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
