# Generated by Django 3.1.3 on 2020-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(default='sleekforum', help_text='Website title', max_length=20, verbose_name='site title'),
        ),
    ]
