# Generated by Django 3.2.6 on 2021-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True, help_text='Website meta-tag description contents', verbose_name='site description'),
        ),
    ]
