# Generated by Django 3.1 on 2020-08-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='captcha',
            field=models.BooleanField(default=False, help_text='Turn on/off captcha on pages'),
        ),
        migrations.AddField(
            model_name='setting',
            name='posts_per_thread',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='setting',
            name='threads_per_page',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
