# Generated by Django 3.2.6 on 2021-09-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_setting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='is_under_maintenance',
            field=models.BooleanField(help_text='Determine if site is under maintenance', null=True, verbose_name='maintenance status'),
        ),
    ]
