# Generated by Django 3.1 on 2020-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200913_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(help_text='website title', max_length=20, verbose_name='site title'),
        ),
    ]
