# Generated by Django 3.1 on 2020-08-22 12:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='title')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), blank=True, null=True, size=None)),
                ('pin', models.IntegerField(choices=[(0, 'Do not pin thread'), (1, 'Pin thread within category'), (2, 'Pin thread globally')], default=0, verbose_name='pin thread')),
                ('prefix', models.IntegerField(choices=[(0, 'Default'), (1, 'Help'), (2, 'Discussion'), (3, 'Info')], default=0, verbose_name='prefix')),
                ('slug', models.SlugField(blank=True, editable=False, verbose_name='slug')),
                ('content', models.TextField(unique_for_date='created', verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, verbose_name='lock thread')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hide thread')),
                ('is_editable', models.BooleanField(default=True, verbose_name='allow edit')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='total likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='total dislikes')),
                ('shares', models.PositiveIntegerField(default=0, verbose_name='total shares')),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='categories.category', verbose_name='category')),
                ('starter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='starter')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['id', 'slug'], name='index_id_slug_on_thread'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_title_on_thread'),
        ),
    ]
