# Generated by Django 3.1 on 2020-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='thread',
            name='index_id_slug_on_thread',
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['id', 'slug'], name='idx_id_slug_on_thread'),
        ),
    ]
