# Generated by Django 3.1 on 2020-08-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20200824_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='is_editable',
        ),
        migrations.AddField(
            model_name='thread',
            name='angries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='happies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='sads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='wows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
