# Generated by Django 3.1 on 2020-08-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
