# Generated by Django 3.1 on 2020-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20200827_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='funnies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='loves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
