# Generated by Django 3.1.6 on 2021-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20210424_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadview',
            name='views',
            field=models.IntegerField(default=0, help_text='View count per thread', verbose_name='Views'),
        ),
    ]
