# Generated by Django 3.1.6 on 2021-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blogs/categories/covers', verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='blogs/categories/icons', verbose_name='image'),
        ),
    ]
