version: "3.8"
services:

  sleekforum:
    build:
      context: src
    networks:
      - backend
      - webserver
    env_file:
      - ./configs/env/postgres.env
      - ./configs/env/sleekforum.env
    volumes:
      - ./src:/srv/http/sleekforum

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgres/data
    networks:
      - backend
    env_file:
      - ./configs/env/postgres.env
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./src/static:/srv/ftp/sleekforum/static
      - ./src/media:/srv/ftp/sleekforum/media
    ports:
      - "4042:4042"

networks:
  backend
  webserver

volumes:
  pg_data: