version: "3.8"

services:
  sleekforum:
    build:
      context: src
      args:
        sleekforum_user: sleekforum
        sleekforum_environment: staging
    networks:
      - db
      - webserver
    restart: unless-stopped
    env_file:
      - ./configs/env/postgres.env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./src:/srv/http/${sleekforum_user:-sleekforum}:z
    depends_on:
      - postgres
    ports:
      - "8000:4042"

  postgres:
    image: postgres
    networks:
      - db
    restart: always
    volumes:
      - pg_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=sleekforum_db
      - POSTGRES_USER=sleekforum_user
      - POSTGRES_PASSWORD=sleekforum_password

  nginx:
    build:
      context: nginx
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src/static:/srv/ftp/sleekforum/static:z
      - ./src/media:/srv/ftp/sleekforum/media:z
    networks:
      - webserver
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - sleekforum

networks:
  db:
  webserver:

volumes:
  pg_data: