# Generated by Django 3.1.6 on 2021-02-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20210212_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chats.privatemessage', verbose_name='parent message'),
        ),
    ]
