# Generated by Django 3.1.6 on 2021-02-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20210212_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'get_latest_by': 'date_sent', 'ordering': ['date_sent']},
        ),
    ]
