# Generated by Django 3.2.6 on 2021-09-01 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20210226_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date friend request was sent', verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='Date became friends / Date request was accepted', verbose_name='Date accepted'),
        ),
    ]
