# Generated by Django 3.1.2 on 2020-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_record', models.DateTimeField()),
            ],
            options={
                'ordering': ['-visit_record'],
                'get_latest_by': 'visit_record',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
