# Generated by Django 3.1 on 2020-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='phone number can start with + but no space', max_length=15, verbose_name='Phone number'),
        ),
    ]
