# Generated by Django 3.1.2 on 2020-10-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201023_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
