# Generated by Django 3.1 on 2020-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200827_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, help_text='Birth date in yyyy-mm-dd format', null=True, verbose_name='Date of Birth'),
        ),
    ]
