# Generated by Django 3.1 on 2020-09-03 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200827_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time user was last active', verbose_name='Last time seen'),
        ),
    ]
