# Generated by Django 3.1 on 2020-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200820_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Whatsapp ID with +country_code', max_length=20, verbose_name='Whatsapp ID'),
        ),
    ]
