# Generated by Django 3.1 on 2020-08-20 09:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200820_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Hobbies separated by comma', null=True, size=None, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number can start with + but no space', max_length=15, verbose_name='Phone number'),
        ),
    ]
