# Generated by Django 3.1 on 2020-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200820_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='A short brief of you that will show in forum', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, help_text='Birth date in yyyy-mm-dd format', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', help_text='Facebook Profile URL', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, default='https://twitter.com/@', help_text='Twitter URL', verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default='https://sleekforum.com', help_text='URL of your website, blog or portfolio', verbose_name='Website'),
        ),
    ]
