# Generated by Django 3.1 on 2020-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200820_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='A description about you. Max: 500 chars', max_length=500, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, help_text='A short brief of you that will show in forum'),
        ),
    ]
