version: "3.8"
services:
  sleekforum:
    build:
      context: .
      args:
        sleekforum_environment: production
    restart: unless-stopped
    volumes:
      - "./src:/srv/http/sleekforum:z"
    environment:
      - SLEEKFORUM_DB_HOST=postgres
    env_file:
      - ./configs/env/sleekforum.env
    networks:
      - db
      - cache
    depends_on:
      - postgres

  postgres:
    image: postgres
    networks:
      - db
    env_file:
      - ./configs/env/postgres.env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - cache
    volumes:
      - cached_data:/data


networks:
  db:
  cache:

volumes:
  cached_data:
  pg_data: