# Generated by Django 3.1.3 on 2020-11-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reaction', models.CharField(choices=[('ANGRY', 'Angry'), ('DISLIKE', 'Dislike'), ('HAPPY', 'Happy'), ('LIKE', 'Like'), ('LOVE', 'Love'), ('SAD', 'Sad'), ('WOW', 'Wow')], max_length=7, verbose_name='Reaction')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Reactions',
            },
        ),
    ]
