# Generated by Django 3.1 on 2020-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='action',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('SAD', 'Sad'), ('HAPPY', 'Happy'), ('LOVE', 'Love'), ('ANGRY', 'Angry'), ('WOW', 'Wow')], default=None, max_length=8, verbose_name='Reaction'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content_type', 'object_id'], name='index_ct_id'),
        ),
    ]
