# Generated by Django 3.1 on 2020-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200827_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name_plural': 'Reactions'},
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='index_ct_id',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('ANGRY', 'Angry'), ('DISLIKE', 'Dislike'), ('HAPPY', 'Happy'), ('LIKE', 'Like'), ('LOVE', 'Love'), ('SAD', 'Sad'), ('WOW', 'Wow')], max_length=7, verbose_name='Reaction'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'reaction', 'content_type', 'object_id'), name='unique_user_activity'),
        ),
    ]
