# Generated by Django 3.1.6 on 2021-04-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210425_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
