# Generated by Django 3.2.5 on 2021-07-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0006_auto_20210723_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity.notification',),
        ),
    ]
